### ISSUE TITLE
 No Flatpak manifest found in this workspace

### ISSUE THREAD

**Issue by mijorus** [bilelmoussaoui/flatpak-vscode#229] opened 2023-12-29 19:03 UTC
```
2023-12-29 20:02:10.883 [error] Error: No Flatpak manifest found in this workspace.
	at ManifestManager.<anonymous> (/home/lorenzo/.vscode/extensions/bilelmoussaoui.flatpak-vscode-0.0.36/out/manifestManager.js:214:23)
	at Generator.next (<anonymous>)
	at fulfilled (/home/lorenzo/.vscode/extensions/bilelmoussaoui.flatpak-vscode-0.0.36/out/manifestManager.js:5:58) flatpak-vscode.build-and-run {"value":"bilelmoussaoui.flatpak-vscode","_lower":"bilelmoussaoui.flatpak-vscode"}
```

From the same folder, GNOME Builder runs just file

**Comment by mijorus** [comment] 2023-12-30 16:57
I dug a little deeper on this.
Apparently, the issue seems to be the fact that, for some reason, Code is not activating the extension:

```
bilelmoussaoui.flatpak-vscode, startup: false, activationEvent: 'workspaceContains:**/*.{json,yaml,yml}'
```

**Comment by SeaDve** [comment] 2023-12-31 00:13
The manifest may also be a good start. Is it possible to show it here?

**Comment by bilelmoussaoui** [comment] 2024-01-21 19:12
Any updates on this one?

**Comment by mijorus** [comment] 2024-01-23 07:41
> Any updates on this one?

Not really, it still happens but I don't know why

**Comment by bilelmoussaoui** [comment] 2024-01-23 07:56
Yes but we would need a way to reproduce it like sharing the manifest with us or the project itself if it is open source.

**Comment by vixalien** [comment] 2024-07-14 14:53
I'm having this issue persistently too. I don't know what exactly I changed. but Flatpak VSCode will now consistently ignore my build manifest until I move it to a separate directory and then move it back while VSCode is running.

This is extremely challenging because it means that Flatpak VSCode will now then recompile everything.

This could potentially be fixed by adding a command to manually re-lookup manifests in the project.

**Comment by mijorus** [comment] 2024-07-15 08:14
I realized that simply by renaming the file is enough to trigger a rescan

**Comment by vixalien** [comment] 2024-07-15 16:33
Yeah but that triggers a rebuild of all the modules

Le lun. 15 juil. 2024 à 10:14, Lorenzo Paderi ***@***.***> a
écrit :

**Comment by bilelmoussaoui** [comment] 2024-08-18 18:17
I think https://github.com/bilelmoussaoui/flatpak-vscode/pull/239 should fix the issue for you.

**Closed by bilelmoussaoui** 2024-08-18 18:17 UTC
