### ISSUE TITLE
rust-analyzer is using all memory

### ISSUE THREAD

**Issue by abergmeier** [bilelmoussaoui/flatpak-vscode#226] opened 2023-11-20 21:53 UTC
When I open a rust project in VSC it takes around 4GB of memory.
When I open a rust project with VSC and flatpak rust-analyzer takes all my memory (16GB) and apps then become unresponsive and crash.

**Comment by bilelmoussaoui** [comment] 2024-01-21 19:15
I think it is a duplicate of https://github.com/bilelmoussaoui/flatpak-vscode/issues/222

**Closed by bilelmoussaoui** 2024-01-21 19:15 UTC
