### ISSUE TITLE
Run button does nothing when app has not been built yet

### ISSUE THREAD

**Issue by Hofer-Julian** [bilelmoussaoui/flatpak-vscode#134] opened 2022-03-05 11:34 UTC
When the triangle "run" button is being pressed without building the app first nothing happens.
Ideally it would build and then run the app like Builder does, but if that's hard to do a warning would suffice as well.

**Comment by SeaDve** [comment] 2022-03-05 11:36
Indeed, the issue is being tracked in #63 and #73. I'm thinking of improving the pipeline system to be more extensible and simpler.

**Comment by Hofer-Julian** [comment] 2022-03-05 11:38
> Indeed, the issue is being tracked in #63 and #73. 

I see, feel free to close this issue then if you feel like its already covered :)

**Comment by SeaDve** [comment] 2022-03-05 11:55
Adding a warning message would be great though, and close this once it is merged

**Closed** 2022-03-05 12:12 UTC
