### ISSUE TITLE
Clicking on select manifest doesn't work

### ISSUE THREAD

**Issue by bilelmoussaoui** [bilelmoussaoui/flatpak-vscode#86] opened 2022-02-27 08:07 UTC
I opened Contrast (cloned from upstream) and no manifest was automatically selected, clicking on the status bar item shows 
```
command 'flatpak-vscode.select-manifest' not found
```
cc @SeaDve

**Comment by SeaDve** [comment] 2022-02-27 08:10
does the select-manifest in the command bar works?

**Comment by bilelmoussaoui** [comment] 2022-02-27 08:12
Same error here,it seems like the manifest search is broken somehow. Restarting the window makes it capable of finding the manifest after a few tries

**Comment by SeaDve** [comment] 2022-02-27 10:38
Not finding the select-manifest command is weird since it is registered no matter what

**Comment by SeaDve** [comment] 2022-02-27 12:06
Does contrast btw has two manifests?

**Comment by bilelmoussaoui** [comment] 2022-02-27 12:10
No it only has one

**Comment by SeaDve** [comment] 2022-02-27 12:13
tried a freshly cloned `git@gitlab.gnome.org:World/design/contrast.git` but wasn't able to reproduce it. A manifest is automatically selected (`org.gnome.design.Contrast.Devel`).

**Comment by SeaDve** [comment] 2022-02-27 12:22
It may be you clicked the statusBarItem too early?

**Comment by bilelmoussaoui** [comment] 2022-02-27 12:24
That is an option but then the status item shouldn't be there until the findManifest promise is resolved

**Comment by SeaDve** [comment] 2022-02-27 12:31
> That is an option but then the status item shouldn't be there until the findManifest promise is resolved

That makes sense. We should also probably load all commands first before doing anything like waiting promises to prevent `command 'flatpak-vscode.select-manifest' not found`

**Comment by bilelmoussaoui** [comment] 2022-02-28 12:08
This still happens here for some cases where the manifest is just never found and after reloading the window it is properly detected and everything works as expected. So there is probably some issue in the findManifests logic somewhere.

**Comment by SeaDve** [comment] 2022-02-28 12:11
Is the debug console outputting something?

**Comment by bilelmoussaoui** [comment] 2022-02-28 12:13
Oh I see, we assume jsonc will be the languageID for commented json but that is not the case, it shows `json` so we fail to parse the manifest and move on. I would suggest always assuming it is a commented json then

**Comment by SeaDve** [comment] 2022-02-28 12:15
Isn't it weird though that it is not always failing?

**Comment by bilelmoussaoui** [comment] 2022-02-28 12:16
for some cases yes, maybe the way vscode detects the language id is flawed

**Comment by bilelmoussaoui** [comment] 2022-02-28 12:16
there might be an unrelated issue though

**Comment by SeaDve** [comment] 2022-02-28 12:17
afaik JSONC can also handle normal json, so maybe try routing everything to JSONC parser

**Comment by bilelmoussaoui** [comment] 2022-03-01 08:09
This should be fixed now no?

**Comment by SeaDve** [comment] 2022-03-01 08:10
Maybe until #102 is merged

**Closed** 2022-03-01 08:47 UTC
